name: LVoiceMute
version: 0.1a
main: wtf.lucasmellof.voicemute.LVoiceMute
author: Lucasmellof(Carmello)
website: https://lucasmellof.wtf
commands:
  checkvoicemute:
    permission: lvoicemute.checkmute
  voicereload:
    permission: lvoicemute.reload
  unvoicemute:
    permission: lvoicemute.unmute
  voicemute:
    permission: lvoicemute.mute